### 错误
> 在Go中有一部分函数总是能成功的运行。比如strings.Contains和strconv.FormatBool函数，对各种可能的输入都做了良好的处理，使得运行时几乎不会失败，除非遇到灾难性的、不可预料的情况，比如运行时的内存溢出。导致这种错误的原因很复杂，难以处理，从错误中恢复的可能性也很低。

#### 第一种策略：
```go
value, ok := cache.Lookup(key)
if !ok {
    // ...cache[key] does not exist…
}
```

```go
// 打印
fmt.Println(err)
fmt.Printf("%v", err)
```


#### 第二种策略：
```go
// fmt.Errorf函数使用fmt.Sprintf格式化错误信息并返回
doc, err := html.Parse(resp.Body)
resp.Body.Close()
if err != nil {
    return nil, fmt.Errorf("parsing %s as HTML: %v", url,err)
}

// (In function main.)
if err := WaitForServer(url); err != nil {
    fmt.Fprintf(os.Stderr, "Site is down: %v\n", err)
    os.Exit(1)
}
```

#### 第三种策略：
```go
// 调用log.Fatalf可以更简洁的代码达到与上文相同的效果。log中的所有函数，都默认会在错误信息之前输出时间信息。
if err := WaitForServer(url); err != nil {
    log.Fatalf("Site is down: %v\n", err)
}
```

``` go
// 我们可以设置log的前缀信息屏蔽时间信息，一般而言，前缀信息会被设置成命令名。
log.SetPrefix("wait: ")
log.SetFlags(0)

if err := Ping(); err != nil {
    log.Printf("ping failed: %v; networking disabled",err)
}
```


#### 第四种策略：
有时，我们只需要输出错误信息就足够了，不需要中断程序的运行。我们可以通过log包提供函数
```go
// 通过log包提供函数
if err := Ping(); err != nil {
    log.Printf("ping failed: %v; networking disabled",err)
}

// 或者标准错误流输出错误信息。
if err := Ping(); err != nil {
    fmt.Fprintf(os.Stderr, "ping failed: %v; networking disabled\n", err)
}
```


#### 第五种策略：
也是最后一种策略：我们可以直接忽略掉错误。
```go
dir, err := ioutil.TempDir("", "scratch")
if err != nil {
    return fmt.Errorf("failed to create temp dir: %v",err)
}
// ...use temp dir…
os.RemoveAll(dir) // ignore errors; $TMPDIR is cleaned periodically
```


### EOF
io包保证任何由文件结束引起的读取失败都返回同一个错误——io.EOF，该错误在io包中定义：
```go
package io

import "errors"

// EOF is the error returned by Read when no more input is available.
var EOF = errors.New("EOF")
```
**调用者只需通过简单的比较，就可以检测出这个错误。**
``` go
in := bufio.NewReader(os.Stdin)
for {
    r, _, err := in.ReadRune()
    if err == io.EOF {
        break // finished reading
    }
    if err != nil {
        return fmt.Errorf("read failed:%v", err)
    }
    // ...use r…
}
```